[build]
builder = "dockerfile"
dockerfilePath = "infrastructure/docker/backend/Dockerfile"

[deploy]
startCommand = "/app/app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
